"""fix_assignment_field_name

Revision ID: 11e1ef046fa4
Revises: eb918c998718
Create Date: 2026-07-08 17:59:32.070874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11e1ef046fa4'
down_revision: Union[str, Sequence[str], None] = 'eb918c998718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('due_datetime', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('assignments_subject_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'subjects', ['subject_id'], ['subject_id'], ondelete='CASCADE')
    op.drop_column('assignments', 'due_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_subject_id_fkey'), 'assignments', 'subjects', ['subject_id'], ['subject_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('assignments', 'due_datetime')
    # ### end Alembic commands ###
