"""add_average_grade_column

Revision ID: 78ebdfb63a67
Revises: f9ce2b95a40c
Create Date: 2026-07-07 20:20:51.149494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ebdfb63a67'
down_revision: Union[str, Sequence[str], None] = 'f9ce2b95a40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('average_grade', sa.Float(), server_default='0.0', nullable=False))
    op.drop_constraint(op.f('subjects_user_id_fkey'), 'subjects', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('subjects_user_id_fkey'), 'subjects', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('subjects', 'average_grade')
    # ### end Alembic commands ###
